version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb-container"
    expose:
      - 27017
  nest-app:
    build: ./app
    container_name: "nest-app-container"
    depends_on:
      - mongodb
    links:
      - mongodb
    expose:
      - 3000
  angular-app:
    build: ./app-frontend
    container_name: "angular-app-container"
    expose:
      - 4200
  nginx-load-balancer:
    build: ./nginx
    container_name: "nginx-load-balancer-container"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nest-app
      - angular-app
