version: "0.0.1"
services:
  nest-app:
    build: ./app
    container_name: "nest-app-container"
    expose:
      - 3000
  angular-app:
    build: ./app-frontend
    container_name: "angular-app-container"
    expose:
      - 4200
  nginx-load-balancer:
    build: ./nginx
    container_name: "nginx-load-balancer-container"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nest-app
      - angular-app
