version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb-local-container"
    volumes:
    - ./data/mongodb:/data/db
    ports:
      - 27017:27017
  nginx-load-balancer:
    build:
      context: ./nginx
      dockerfile: local.Dockerfile
    container_name: "nginx-load-balancer-local-container"
    ports:
      - 80:80
      - 443:443
